/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3132",
        "on-primary": "#ffffff",
        "primary-fixed": "#d6e3ff",
        "on-error": "#ffffff",
        "tertiary-container": "#00697b",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e1e3e4",
        "secondary": "#006e1c",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "background": "#f8f9fa",
        "on-background": "#191c1d",
        "on-tertiary-fixed": "#001f26",
        "surface-container-highest": "#e1e3e4",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#abedff",
        "outline-variant": "#c2c6d4",
        "on-secondary-fixed": "#002204",
        "on-tertiary": "#ffffff",
        "secondary-container": "#91f78e",
        "primary": "#00478d",
        "inverse-primary": "#a9c7ff",
        "outline": "#727783",
        "surface-container-high": "#e7e8e9",
        "surface-dim": "#d9dadb",
        "secondary-fixed": "#94f990",
        "on-primary-container": "#c8daff",
        "surface-container-low": "#f3f4f5",
        "on-secondary-fixed-variant": "#005313",
        "on-secondary-container": "#00731e",
        "on-tertiary-container": "#8ee7ff",
        "tertiary": "#004f5d",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed": "#001b3d",
        "on-tertiary-fixed-variant": "#004e5c",
        "on-primary-fixed-variant": "#00468c",
        "surface": "#f8f9fa",
        "secondary-fixed-dim": "#78dc77",
        "on-surface-variant": "#424752",
        "primary-fixed-dim": "#a9c7ff",
        "tertiary-fixed-dim": "#79d3ea",
        "primary-container": "#005eb8",
        "surface-container": "#edeeef",
        "on-surface": "#191c1d",
        "on-error-container": "#93000a",
        "surface-tint": "#005db6",
        "surface-bright": "#f8f9fa"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
