from .appointment_routes import appointment_bp
from .recommendation_routes import recommendation_bp
from .chatbot_routes import chatbot_bp
from .health_routes import health_bp
from .auth_routes import auth_bp
from .specialist_routes import specialist_bp
from .department_routes import department_bp
from .admin_routes import admin_bp
from .patient_routes import patient_bp
from .queue_routes import queue_bp
