"""Add guardian_email to Patient

Revision ID: 00dfe03e768e
Revises: d630e9a39d5e
Create Date: 2026-04-27 10:21:39.968414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00dfe03e768e'
down_revision = 'd630e9a39d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('guardian_email')

    # ### end Alembic commands ###
