"""Add check-in and check-out times to queue

Revision ID: 0585b8a5d8a0
Revises: 7020960a1d5b
Create Date: 2026-04-25 08:35:24.877541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0585b8a5d8a0'
down_revision = '7020960a1d5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_in_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('check_out_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.drop_column('check_out_time')
        batch_op.drop_column('check_in_time')

    # ### end Alembic commands ###
