"""Remove unique constraint from patient email

Revision ID: 2312bcdeb6a0
Revises: 00dfe03e768e
Create Date: 2026-04-27 10:32:13.714515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2312bcdeb6a0'
down_revision = '00dfe03e768e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('patients_email_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('patients_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
