"""support multiple doctor sessions per day with independent queues

Revision ID: 5644d768b5b4
Revises: 2312bcdeb6a0
Create Date: 2026-04-28 11:16:27.035043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5644d768b5b4'
down_revision = '2312bcdeb6a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_session_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('queue_number', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('appointments_session_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'doctor_sessions', ['doctor_session_id'], ['id'])
        batch_op.drop_column('session_id')

    with op.batch_alter_table('lab_reports', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('doctor_session_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_queue_session_number', ['doctor_session_id', 'queue_number'])
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'doctor_sessions', ['doctor_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_queue_session_number', type_='unique')
        batch_op.drop_column('doctor_session_id')
        batch_op.drop_column('patient_id')

    with op.batch_alter_table('lab_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appointments_session_id_fkey'), 'doctor_sessions', ['session_id'], ['id'])
        batch_op.drop_column('queue_number')
        batch_op.drop_column('doctor_session_id')

    # ### end Alembic commands ###
