"""Add status and completed_at to Queue

Revision ID: 79f2f794d8ef
Revises: 0a5ce5cb188c
Create Date: 2026-03-01 21:47:55.631209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79f2f794d8ef'
down_revision = '0a5ce5cb188c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queues', schema=None) as batch_op:
        batch_op.drop_column('completed_at')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
