"""Add title, email, phone to specialist

Revision ID: 8ec4954218e3
Revises: 8102df7ef852
Create Date: 2026-04-24 13:17:16.959055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec4954218e3'
down_revision = '8102df7ef852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialists', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('email')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
