"""Add guardian fields and dob to Patient

Revision ID: 93e2c618b3ee
Revises: ee4256ae22c4
Create Date: 2026-04-27 09:54:46.165317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93e2c618b3ee'
down_revision = 'ee4256ae22c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dob', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('guardian_nic', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('guardian_relationship', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('guardian_relationship')
        batch_op.drop_column('guardian_phone')
        batch_op.drop_column('guardian_nic')
        batch_op.drop_column('guardian_name')
        batch_op.drop_column('dob')

    # ### end Alembic commands ###
