"""Add guardian_id foreign key to Patient

Revision ID: d630e9a39d5e
Revises: 93e2c618b3ee
Create Date: 2026-04-27 10:07:16.641731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd630e9a39d5e'
down_revision = '93e2c618b3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guardian_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'patients', ['guardian_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('guardian_id')

    # ### end Alembic commands ###
