"""Add face_embedding to Patient

Revision ID: ee4256ae22c4
Revises: 0585b8a5d8a0
Create Date: 2026-04-25 09:05:25.731884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4256ae22c4'
down_revision = '0585b8a5d8a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_embedding', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('face_embedding')

    # ### end Alembic commands ###
